export const GET_USER = "GET_USER";
export const BASEURL = "/sa";

export const ANNOUNCEMENT_LIST_REQUEST = "ANNOUNCEMENT_LIST_REQUEST";
export const ANNOUNCEMENT_DELETE_REQUEST = "ANNOUNCEMENT_DELETE_REQUEST";
export const ANNOUNCEMENT_CREATE_REQUEST = "ANNOUNCEMENT_CREATE_REQUEST";
export const ANNOUNCEMENT_EDIT_REQUEST = "ANNOUNCEMENT_EDIT_REQUEST";

export const CATEGORY_LIST_REQUEST = "CATEGORY_LIST_REQUEST";

export const FORM_LIST_REQUEST = "FORM_LIST_REQUEST";
export const FORM_DELETE_REQUEST = "FORM_DELETE_REQUEST";
export const FORM_CREATE_REQUEST = "FORM_CREATE_REQUEST";
export const FORM_EDIT_REQUEST = "FORM_EDIT_REQUEST";

export const ABOUT_UPDATE_EDITORSTATE = "ABOUT_UPDATE_EDITORSTATE";

export const EVENT_LIST_REQUEST = "EVENT_LIST_REQUEST";
export const EVENT_DELETE_REQUEST = "EVENT_DELETE_REQUEST";
export const EVENT_CREATE_REQUEST = "EVENT_CREATE_REQUEST";
export const EVENT_EDIT_REQUEST = "EVENT_EDIT_REQUEST";

export const EVENT_CATEGORY_LIST_REQUEST = "EVENT_CATEGORY_LIST_REQUEST";

export const BASEAPI = "http://localhost:8080/sa/api";

export const LOGIN_URL = `${BASEAPI}/auth/azureadoauth2`;
export const LOGOUT_URL = `${BASEAPI}/auth/logout`;
