export const GET_USER = "GET_USER";
export const BASEURL = "/sa";

export const ANNOUNCEMENT_LIST_REQUEST = "ANNOUNCEMENT_LIST_REQUEST";
export const ANNOUNCEMENT_DELETE_REQUEST = "ANNOUNCEMENT_DELETE_REQUEST";
export const ANNOUNCEMENT_CREATE_REQUEST = "ANNOUNCEMENT_CREATE_REQUEST";
export const ANNOUNCEMENT_EDIT_REQUEST = "ANNOUNCEMENT_EDIT_REQUEST";

export const CATEGORY_LIST_REQUEST = "CATEGORY_LIST_REQUEST";

export const FORM_LIST_REQUEST = "FORM_LIST_REQUEST";
export const FORM_DELETE_REQUEST = "FORM_DELETE_REQUEST";
export const FORM_CREATE_REQUEST = "FORM_CREATE_REQUEST";
export const FORM_EDIT_REQUEST = "FORM_EDIT_REQUEST";

export const ABOUT_UPDATE_EDITORSTATE = "ABOUT_UPDATE_EDITORSTATE";

export const EVENT_LIST_REQUEST = "EVENT_LIST_REQUEST";
export const EVENT_DELETE_REQUEST = "EVENT_DELETE_REQUEST";
export const EVENT_CREATE_REQUEST = "EVENT_CREATE_REQUEST";
export const EVENT_EDIT_REQUEST = "EVENT_EDIT_REQUEST";

export const EVENT_CATEGORY_LIST_REQUEST = "EVENT_CATEGORY_LIST_REQUEST";

export const RULE_LIST_REQUEST = "RULE_LIST_REQUEST";
export const RULE_DELETE_REQUEST = "RULE_DELETE_REQUEST";
export const RULE_CREATE_REQUEST = "RULE_CREATE_REQUEST";
export const RULE_EDIT_REQUEST = "RULE_EDIT_REQUEST";

export const LINK_LIST_REQUEST = "LINK_LIST_REQUEST";
export const LINK_DELETE_REQUEST = "LINK_DELETE_REQUEST";
export const LINK_CREATE_REQUEST = "LINK_CREATE_REQUEST";
export const LINK_EDIT_REQUEST = "LINK_EDIT_REQUEST";
export const COURSE_LIST_REQUEST = "COURSE_LIST_REQUEST";
export const COURSE_DELETE_REQUEST = "COURSE_DELETE_REQUEST";
export const COURSE_CREATE_REQUEST = "COURSE_CREATE_REQUEST";
export const COURSE_EDIT_REQUEST = "COURSE_EDIT_REQUEST";

export const SCHLINK_LIST_REQUEST = "SCHLINK_LIST_REQUEST";
export const SCHLINK_DELETE_REQUEST = "SCHLINK_DELETE_REQUEST";
export const SCHLINK_CREATE_REQUEST = "SCHLINK_CREATE_REQUEST";
export const SCHLINK_EDIT_REQUEST = "SCHLINK_EDIT_REQUEST";

export const BASEAPI = "http://localhost:8080/sa/api";

export const LOGIN_URL = `${BASEAPI}/auth/azureadoauth2`;
export const LOGOUT_URL = `${BASEAPI}/auth/logout`;
