export const GET_USER = "GET_USER";
export const BASEURL = "/sa";

export const ANNOUNCEMENT_LIST_REQUEST = "ANNOUNCEMENT_LIST_REQUEST";
//export const ANNOUNCEMENT_LIST_SUCCESS = "ANNOUNCEMENT_LIST_SUCCESS";
//export const ANNOUNCEMENT_FAIL = "ANNOUNCEMENT_FAIL";

export const ANNOUNCEMENT_DELETE_REQUEST = "ANNOUNCEMENT_DELETE_REQUEST";
//export const ANNOUNCEMENT_DELETE_SUCCESS = "ANNOUNCEMENT_DELETE_SUCCESS";
//export const ANNOUNCEMENT_DELETE_FAIL = "ANNOUNCEMENT_DELETE_FAIL";

export const ANNOUNCEMENT_CREATE_REQUEST = "ANNOUNCEMENT_CREATE_REQUEST";
//export const ANNOUNCEMENT_CREATE_SUCCESS = "ANNOUNCEMENT_CREATE_SUCCESS";
//export const ANNOUNCEMENT_CREATE_FAIL = "ANNOUNCEMENT_CREATE_FAIL";

export const ANNOUNCEMENT_EDIT_REQUEST = "ANNOUNCEMENT_EDIT_REQUEST";

export const ABOUT_UPDATE_EDITORSTATE = "ABOUT_UPDATE_EDITORSTATE";

export const BASEAPI = "http://localhost:8080/sa/api";

export const LOGIN_URL = `${BASEAPI}/auth/azureadoauth2`;
export const LOGOUT_URL = `${BASEAPI}/auth/logout`;
